//! Arranging the entry points into the review's node tree.

use std::collections::{BTreeMap, BTreeSet};

use super::category::ReviewEntryCategory;
use super::report::{effect_summary, review_checklist};
use super::{REVIEW_PR_TEXT_NODE_ID, ReviewEntryPoint, ReviewNode, ReviewRender, plural};

pub(super) fn build_review_nodes(review: &ReviewRender<'_>) -> Vec<ReviewNode> {
    let mut nodes = Vec::new();
    push_entry_nodes(
        &mut nodes,
        "branch",
        "Full diff against main",
        review.entries,
        review.diff.trim().is_empty(),
    );
    nodes.push(ReviewNode {
        id: "summary".to_string(),
        parent: None,
        depth: 0,
        title: format!(
            "Summary: {} vs {} ({} commits, {} files)",
            review.branch,
            review.base_ref,
            review.commits.len(),
            review.files.len()
        ),
        body: effect_summary(review.files, review.entries, review.commits),
        context: Vec::new(),
    });
    nodes.push(ReviewNode {
        id: "checklist".to_string(),
        parent: None,
        depth: 0,
        title: "Review checklist".to_string(),
        body: review_checklist(review.files, review.entries),
        context: Vec::new(),
    });
    nodes.push(ReviewNode {
        id: REVIEW_PR_TEXT_NODE_ID.to_string(),
        parent: Some("checklist".to_string()),
        depth: 1,
        title: "PR text - generated by LLM (y copy)".to_string(),
        body: Vec::new(),
        context: Vec::new(),
    });
    nodes
}

fn push_entry_nodes(
    nodes: &mut Vec<ReviewNode>,
    prefix: &str,
    title: &str,
    entries: &[ReviewEntryPoint],
    empty: bool,
) {
    let root_id = prefix.to_string();
    nodes.push(ReviewNode {
        id: root_id.clone(),
        parent: None,
        depth: 0,
        title: title.to_string(),
        body: if empty {
            vec!["(empty)".to_string()]
        } else if entries.is_empty() {
            vec!["(only import changes hidden)".to_string()]
        } else {
            Vec::new()
        },
        context: Vec::new(),
    });
    if entries.is_empty() {
        return;
    }
    let groups = entry_groups(entries);
    let parents = entry_group_parents(entries, &groups);
    let category_summaries = review_category_summaries(entries, &groups);
    let tree = EntryTree {
        prefix,
        entries,
        groups: &groups,
        parents: &parents,
    };
    let mut emitted = BTreeSet::new();
    let mut categories = CategoryNodes {
        prefix,
        root_id: &root_id,
        summaries: &category_summaries,
        emitted: BTreeSet::new(),
    };
    for category in ReviewEntryCategory::ALL {
        for (path, group_indices) in groups_by_path(
            groups
                .iter()
                .enumerate()
                .filter(|(group_idx, group)| {
                    parents[*group_idx].is_none()
                        && ReviewEntryCategory::for_path(&group.path) == category
                })
                .map(|(group_idx, _)| group_idx),
            &groups,
        ) {
            let category_id = categories.ensure(nodes, category);
            tree.push_file(nodes, &path, &group_indices, &category_id, 2, &mut emitted);
        }
    }
    for (group_idx, group) in groups.iter().enumerate() {
        let category_id = categories.ensure(nodes, ReviewEntryCategory::for_path(&group.path));
        tree.push_file(
            nodes,
            &group.path,
            &[group_idx],
            &category_id,
            2,
            &mut emitted,
        );
    }
}

#[derive(Debug, Clone, Default)]
struct ReviewCategorySummary {
    files: BTreeSet<String>,
    entries: usize,
    added: usize,
    removed: usize,
}

impl ReviewCategorySummary {
    fn title(&self, category: ReviewEntryCategory) -> String {
        format!(
            "{} ({} file{}, {} entry point{}, +{} -{})",
            category.label(),
            self.files.len(),
            plural(self.files.len()),
            self.entries,
            plural(self.entries),
            self.added,
            self.removed
        )
    }
}

fn review_category_summaries(
    entries: &[ReviewEntryPoint],
    groups: &[EntryGroup],
) -> BTreeMap<ReviewEntryCategory, ReviewCategorySummary> {
    let mut summaries = BTreeMap::<ReviewEntryCategory, ReviewCategorySummary>::new();
    for group in groups {
        let category = ReviewEntryCategory::for_path(&group.path);
        let summary = summaries.entry(category).or_default();
        let (added, removed) = group_totals(entries, group);
        summary.files.insert(group.path.clone());
        summary.entries += 1;
        summary.added += added;
        summary.removed += removed;
    }
    summaries
}

/// Emits a category node the first time that category is asked for, and hands
/// back its id every time.
struct CategoryNodes<'a> {
    prefix: &'a str,
    root_id: &'a str,
    summaries: &'a BTreeMap<ReviewEntryCategory, ReviewCategorySummary>,
    emitted: BTreeSet<ReviewEntryCategory>,
}

impl CategoryNodes<'_> {
    fn ensure(&mut self, nodes: &mut Vec<ReviewNode>, category: ReviewEntryCategory) -> String {
        let id = format!("{}:category:{}", self.prefix, category.id());
        if self.emitted.insert(category) {
            nodes.push(ReviewNode {
                id: id.clone(),
                parent: Some(self.root_id.to_string()),
                depth: 1,
                title: self
                    .summaries
                    .get(&category)
                    .map(|summary| summary.title(category))
                    .unwrap_or_else(|| category.label().to_string()),
                body: Vec::new(),
                context: Vec::new(),
            });
        }
        id
    }
}

struct EntryTree<'a> {
    prefix: &'a str,
    entries: &'a [ReviewEntryPoint],
    groups: &'a [EntryGroup],
    parents: &'a [Option<usize>],
}

impl EntryTree<'_> {
    fn push_file(
        &self,
        nodes: &mut Vec<ReviewNode>,
        path: &str,
        group_indices: &[usize],
        parent_id: &str,
        depth: u16,
        emitted: &mut BTreeSet<usize>,
    ) {
        let pending: Vec<usize> = group_indices
            .iter()
            .copied()
            .filter(|group_idx| !emitted.contains(group_idx))
            .collect();
        if pending.is_empty() {
            return;
        }

        let file_id = format!("{}:file:{}", self.prefix, pending[0]);
        nodes.push(ReviewNode {
            id: file_id.clone(),
            parent: Some(parent_id.to_string()),
            depth,
            title: self.file_title(path),
            body: self.file_patch_body(path),
            context: Vec::new(),
        });
        for group_idx in pending {
            self.push_group(nodes, group_idx, &file_id, depth.saturating_add(1), emitted);
        }
    }

    fn push_group(
        &self,
        nodes: &mut Vec<ReviewNode>,
        group_idx: usize,
        parent_id: &str,
        depth: u16,
        emitted: &mut BTreeSet<usize>,
    ) {
        if !emitted.insert(group_idx) {
            return;
        }

        let group = &self.groups[group_idx];
        let group_id = format!("{}:entry:{group_idx}", self.prefix);
        let location = group
            .indices
            .iter()
            .filter_map(|idx| self.entries[*idx].line)
            .min()
            .map(|line| format!("{}:{line}", group.path))
            .unwrap_or_else(|| group.path.clone());
        nodes.push(ReviewNode {
            id: group_id.clone(),
            parent: Some(parent_id.to_string()),
            depth,
            title: format!(
                "{} in {} - {}",
                location,
                group.symbol,
                entry_group_description(self.entries, group)
            ),
            body: self.group_patch_body(group),
            context: self.group_context(group),
        });

        for child_idx in 0..self.groups.len() {
            if self.parents[child_idx] == Some(group_idx) {
                if self.groups[child_idx].path == group.path {
                    self.push_group(
                        nodes,
                        child_idx,
                        &group_id,
                        depth.saturating_add(1),
                        emitted,
                    );
                } else {
                    self.push_file(
                        nodes,
                        &self.groups[child_idx].path,
                        &[child_idx],
                        &group_id,
                        depth.saturating_add(1),
                        emitted,
                    );
                }
            }
        }
    }

    fn file_title(&self, path: &str) -> String {
        let mut entry_count = 0usize;
        let mut added = 0usize;
        let mut removed = 0usize;
        for group in self.groups.iter().filter(|group| group.path == path) {
            let (group_added, group_removed) = group_totals(self.entries, group);
            entry_count += 1;
            added += group_added;
            removed += group_removed;
        }
        let noun = if entry_count == 1 {
            "entry point"
        } else {
            "entry points"
        };
        format!("{path} - {entry_count} {noun} (+{added} -{removed})")
    }

    fn file_patch_body(&self, path: &str) -> Vec<String> {
        self.groups
            .iter()
            .filter(|group| group.path == path)
            .flat_map(|group| {
                group
                    .indices
                    .iter()
                    .flat_map(|idx| self.entries[*idx].patch.iter().cloned())
            })
            .collect()
    }

    fn group_patch_body(&self, group: &EntryGroup) -> Vec<String> {
        group
            .indices
            .iter()
            .flat_map(|idx| self.entries[*idx].patch.iter().cloned())
            .collect()
    }

    fn group_context(&self, group: &EntryGroup) -> Vec<String> {
        group
            .indices
            .iter()
            .flat_map(|idx| self.entries[*idx].context.iter().cloned())
            .collect()
    }
}

struct EntryGroup {
    path: String,
    symbol: String,
    indices: Vec<usize>,
}

/// The added and removed line counts across every hunk in the group.
fn group_totals(entries: &[ReviewEntryPoint], group: &EntryGroup) -> (usize, usize) {
    group.indices.iter().fold((0, 0), |(added, removed), idx| {
        (added + entries[*idx].added, removed + entries[*idx].removed)
    })
}

fn entry_group_description(entries: &[ReviewEntryPoint], group: &EntryGroup) -> String {
    let (added, removed) = group_totals(entries, group);
    if group.indices.len() == 1 {
        entries[group.indices[0]].description.clone()
    } else {
        format!(
            "{} hunks update this entry point (+{added} -{removed})",
            group.indices.len()
        )
    }
}

fn entry_groups(entries: &[ReviewEntryPoint]) -> Vec<EntryGroup> {
    let mut groups = Vec::<EntryGroup>::new();
    for (idx, entry) in entries.iter().enumerate() {
        if let Some(group) = groups
            .iter_mut()
            .find(|group| group.path == entry.path && group.symbol == entry.symbol)
        {
            group.indices.push(idx);
        } else {
            groups.push(EntryGroup {
                path: entry.path.clone(),
                symbol: entry.symbol.clone(),
                indices: vec![idx],
            });
        }
    }
    groups
}

fn groups_by_path<I>(indices: I, groups: &[EntryGroup]) -> Vec<(String, Vec<usize>)>
where
    I: IntoIterator<Item = usize>,
{
    let mut files = Vec::<(String, Vec<usize>)>::new();
    for idx in indices {
        let path = &groups[idx].path;
        if let Some((_, group_indices)) = files.iter_mut().find(|(candidate, _)| candidate == path)
        {
            group_indices.push(idx);
        } else {
            files.push((path.clone(), vec![idx]));
        }
    }
    files
}

fn entry_group_parents(entries: &[ReviewEntryPoint], groups: &[EntryGroup]) -> Vec<Option<usize>> {
    groups
        .iter()
        .enumerate()
        .map(|(callee_idx, callee)| {
            let callable = callable_symbol_name(&callee.symbol)?;
            groups
                .iter()
                .enumerate()
                .filter(|(caller_idx, _)| *caller_idx != callee_idx)
                .filter(|(_, caller)| {
                    ReviewEntryCategory::for_path(&caller.path)
                        == ReviewEntryCategory::for_path(&callee.path)
                })
                .filter(|(_, caller)| entry_group_references(entries, caller, &callable))
                .map(|(caller_idx, _)| caller_idx)
                .next()
        })
        .collect()
}

fn entry_group_references(
    entries: &[ReviewEntryPoint],
    group: &EntryGroup,
    callable: &str,
) -> bool {
    group
        .indices
        .iter()
        .any(|idx| patch_references_callable(&entries[*idx].patch, callable))
}

fn patch_references_callable(patch: &[String], callable: &str) -> bool {
    patch
        .iter()
        .filter_map(|line| {
            line.strip_prefix('+')
                .or_else(|| line.strip_prefix(' '))
                .or_else(|| line.strip_prefix('-'))
        })
        .any(|line| line_references_callable(line, callable))
}

fn line_references_callable(line: &str, callable: &str) -> bool {
    line.match_indices(callable).any(|(idx, _)| {
        let before = line[..idx].chars().next_back();
        let after = line[idx + callable.len()..].chars().next();
        !before.is_some_and(is_ident_continue) && !after.is_some_and(is_ident_continue)
    })
}

fn is_ident_continue(ch: char) -> bool {
    ch == '_' || ch.is_ascii_alphanumeric()
}

fn callable_symbol_name(symbol: &str) -> Option<String> {
    let rest = symbol
        .strip_prefix("fn ")
        .or_else(|| symbol.strip_prefix("async fn "))
        .or_else(|| symbol.strip_prefix("fun "))?;
    let name = rest
        .split(|ch: char| ch == '(' || ch == '<' || ch == ':' || ch == '{' || ch.is_whitespace())
        .next()
        .unwrap_or(rest)
        .trim();
    (!name.is_empty()).then(|| name.to_string())
}

#[cfg(test)]
mod tests {
    use super::super::ReviewFile;
    use super::*;

    #[test]
    fn callable_symbol_name_strips_signature_punctuation() {
        assert_eq!(callable_symbol_name("fn foo()"), Some("foo".into()));
        assert_eq!(
            callable_symbol_name("async fn build<T>(x: T)"),
            Some("build".into())
        );
        assert_eq!(
            callable_symbol_name("fun handle(x: Int)"),
            Some("handle".into())
        );
        assert_eq!(callable_symbol_name("struct AppState"), None);
    }

    #[test]
    fn line_references_callable_only_matches_whole_idents() {
        assert!(line_references_callable("    foo();", "foo"));
        assert!(line_references_callable("foo + 1", "foo"));
        // No match when surrounded by ident chars.
        assert!(!line_references_callable("foobar();", "foo"));
        assert!(!line_references_callable("let _foo = 1;", "foo"));
    }

    #[test]
    fn build_review_nodes_groups_files_by_review_category() {
        let entries = vec![
            review_entry("src/main/kotlin/App.kt"),
            review_entry("src/test/kotlin/AppTest.kt"),
            review_entry("src/main/resources/db/migration/V1__app.sql"),
            review_entry("docs/app.md"),
            review_entry(".gitignore"),
        ];
        let files = entries
            .iter()
            .map(|entry| ReviewFile {
                status: "M".into(),
                path: entry.path.clone(),
                old_path: None,
            })
            .collect::<Vec<_>>();
        let commits = vec!["abc123 update review".to_string()];
        let render = ReviewRender {
            branch: "feature",
            base_ref: "main",
            merge_base: "",
            commits: &commits,
            files: &files,
            stat: "",
            entries: &entries,
            diff: "diff",
        };

        let nodes = build_review_nodes(&render);

        assert!(
            nodes
                .iter()
                .any(|node| node.id == "branch:category:production"
                    && node.parent.as_deref() == Some("branch")
                    && node.depth == 1
                    && node.title == "Production (1 file, 1 entry point, +1 -0)"),
            "{nodes:#?}"
        );
        assert!(
            nodes.iter().any(|node| node.id == "branch:category:tests"
                && node.parent.as_deref() == Some("branch")
                && node.title == "Tests (1 file, 1 entry point, +1 -0)"),
            "{nodes:#?}"
        );
        assert!(
            nodes
                .iter()
                .any(|node| node.id == "branch:category:migrations"
                    && node.parent.as_deref() == Some("branch")
                    && node.title == "Migrations (1 file, 1 entry point, +1 -0)"),
            "{nodes:#?}"
        );
        assert!(
            nodes.iter().any(|node| node.id == "branch:category:docs"
                && node.parent.as_deref() == Some("branch")
                && node.title == "Docs (1 file, 1 entry point, +1 -0)"),
            "{nodes:#?}"
        );
        assert!(
            nodes.iter().any(|node| node.id == "branch:category:other"
                && node.parent.as_deref() == Some("branch")
                && node.title == "Other (1 file, 1 entry point, +1 -0)"),
            "{nodes:#?}"
        );

        let production_file = nodes
            .iter()
            .find(|node| node.title.starts_with("src/main/kotlin/App.kt - "))
            .expect("production file node");
        assert_eq!(
            production_file.parent.as_deref(),
            Some("branch:category:production")
        );
        assert_eq!(production_file.depth, 2);

        let test_file = nodes
            .iter()
            .find(|node| node.title.starts_with("src/test/kotlin/AppTest.kt - "))
            .expect("test file node");
        assert_eq!(test_file.parent.as_deref(), Some("branch:category:tests"));
        assert_eq!(test_file.depth, 2);

        assert!(
            nodes.iter().any(|node| node.id == REVIEW_PR_TEXT_NODE_ID
                && node.parent.as_deref() == Some("checklist")
                && node.depth == 1
                && node.title.contains("PR text")),
            "{nodes:#?}"
        );
    }

    #[test]
    fn build_review_nodes_keeps_called_production_file_in_production_category() {
        let entries = vec![
            ReviewEntryPoint {
                path: "src/main/kotlin/app/service/BalanceService.kt".into(),
                line: Some(162),
                symbol: "fun updateBalanceCache".into(),
                description: "updates cache behavior (+1 -1)".into(),
                hunk: "@@ -162 +162 @@".into(),
                patch: vec![
                    "@@ -162 +162 @@".into(),
                    "-    oldCache(items)".into(),
                    "+    newCache(items)".into(),
                ],
                context: Vec::new(),
                added: 1,
                removed: 1,
            },
            ReviewEntryPoint {
                path: "src/test/kotlin/app/service/BalanceServiceTest.kt".into(),
                line: Some(332),
                symbol: "fun updateBalanceCacheTest".into(),
                description: "updates assertions (+2 -2)".into(),
                hunk: "@@ -332 +332 @@".into(),
                patch: vec![
                    "@@ -332 +332 @@".into(),
                    "     service.updateBalanceCache(items)".into(),
                    "-    assertThat(balance).isEqualTo(oldValue)".into(),
                    "+    assertThat(balance).isEqualTo(newValue)".into(),
                ],
                context: Vec::new(),
                added: 1,
                removed: 1,
            },
        ];
        let files = entries
            .iter()
            .map(|entry| ReviewFile {
                status: "M".into(),
                path: entry.path.clone(),
                old_path: None,
            })
            .collect::<Vec<_>>();
        let commits = vec!["abc123 update cache".to_string()];
        let render = ReviewRender {
            branch: "feature",
            base_ref: "main",
            merge_base: "",
            commits: &commits,
            files: &files,
            stat: "",
            entries: &entries,
            diff: "diff",
        };

        let nodes = build_review_nodes(&render);

        let production_file = nodes
            .iter()
            .find(|node| {
                node.title
                    .starts_with("src/main/kotlin/app/service/BalanceService.kt - ")
            })
            .expect("production file node");
        assert_eq!(
            production_file.parent.as_deref(),
            Some("branch:category:production"),
            "{nodes:#?}"
        );

        let test_file = nodes
            .iter()
            .find(|node| {
                node.title
                    .starts_with("src/test/kotlin/app/service/BalanceServiceTest.kt - ")
            })
            .expect("test file node");
        assert_eq!(
            test_file.parent.as_deref(),
            Some("branch:category:tests"),
            "{nodes:#?}"
        );
    }

    fn review_entry(path: &str) -> ReviewEntryPoint {
        ReviewEntryPoint {
            path: path.into(),
            line: Some(1),
            symbol: "file scope".into(),
            description: "adds item (+1 -0)".into(),
            hunk: "@@ -1 +1 @@".into(),
            patch: vec!["@@ -1 +1 @@".into(), "-old".into(), "+new".into()],
            context: Vec::new(),
            added: 1,
            removed: 0,
        }
    }
}
